### ISSUE TITLE
How to run "rails assets:precompile" during build?

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/ruby#470]
Amongst other things, the old ruby-buildpack would run run `rake assets:precompile` to build a Rails app's assets.

How can I get a command like this to run amidst the building of my Rails app?

Currently I'm running:

```
$ cat plan.toml
[[requires]]
  name = "node"
  version = "~12"
[requires.metadata]
  launch = true

$ pack build myapp --buildpack gcr.io/paketo-buildpacks/ruby --buildpack gcr.io/paketo-buildpacks/node-engine --buildpack https://github.com/paketo-community/build-plan/releases/download/v0.0.8/build-plan-v0.0.8.tgz --builder paketobuildpacks/builder:full

**Comment by sophiewigmore** [comment]
@drnic right now, this isn't natively supported in the buildpack. You could try adding a Procfile into your app, and then the [procfile buildpack](https://github.com/paketo-buildpacks/procfile) will get pulled in and overwrite the start command with that. Let me know if this works for you!

**Comment by ryanmoran** [comment]
There is no current support for this, but I've written up an RFC to introduce a new buildpack into the Ruby family that will handle this: https://github.com/paketo-buildpacks/ruby/pull/475.

**Comment by genevieve** [comment]
I've implemented the buildpack for the RFC: https://github.com/genevieve/rails-assets

**Comment by ryanmoran** [comment]
@paketo-buildpacks/ruby-maintainers can we get some 👀 on this?

**Comment by ForestEckhardt** [comment]
@genevieve I just have a couple of quick clarifying questions.
1. Do you need to always require `yarn` during detect or could you only need `npm`?
1. Does the `RAILS_ENV` environment variable need to be set as a launch time variable?

**Comment by genevieve** [comment]
Hey Forest! Both of these answers are prefixed with _I think_ because when I didn't do these things, there were errors. That is to say, there could be alternative approaches to solving them.

1. Do you need to always require yarn during detect or could you only need npm?
I think either could work. I chose yarn because the failure when trying to build the app was that yarn was not found and was needed so I chose yarn.
2. Does the RAILS_ENV environment variable need to be set as a launch time variable?
Yes I believe it's needed during precompilation and at runtime:
- https://devcenter.heroku.com/articles/rails-asset-pipeline#compiling-assets-locally
When its not set, we see errors like:
```
/layers/paketo-buildpacks_bundle-install/gems/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
```

**Comment by genevieve** [comment]
Updating this thread - https://github.com/paketo-buildpacks/rails-assets

**Comment by sophiewigmore** [comment]
Closing since the `rails-assets` buildpack is now a part of the Ruby buildpack.
