### ISSUE TITLE
Upgrade to buildpack API v0.5

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/ruby#578]
The  Ruby buildpack currently uses CNB Buildpacks API v0.2. The CNB spec has evolved since then. To take advantage of more upstream features, the buildpack should be upgraded to API v0.5.  

Since the buildpack is composed of many implementation buildpacks, the implementation buildpacks should also be updated to v0.5. Here is the list of related issues to bump the version in each of the Ruby-specific implementation buildpacks:
https://github.com/paketo-buildpacks/bundler/issues/193
https://github.com/paketo-buildpacks/mri/issues/210
https://github.com/paketo-buildpacks/passenger/issues/98
https://github.com/paketo-buildpacks/puma/issues/158
https://github.com/paketo-buildpacks/rackup/issues/152
https://github.com/paketo-buildpacks/rake/issues/100
https://github.com/paketo-buildpacks/rails-assets/issues/59
https://github.com/paketo-buildpacks/thin/issues/144
https://github.com/paketo-buildpacks/unicorn/issues/145

**Comment by fg-j** [comment]
It'd be great to perform this upgrade so that the buildpack can take advantage of the [default process with additional arguments](https://buildpacks.io/docs/app-developer-guide/run-an-app/#default-process-type-with-additional-arguments) feature supported by the lifecycle in buildpack API v0.4. This would enable workflows like building a rake-task-running image and then choosing the task at run-time with:
```
docker run -it rake-app my_non_default_task
```

That's an improvement over the current, clunkier, way of accomplishing the same thing:
```
docker run -it --entrypoint=launcher rake-app bundle exec rake my_non_default_task
```

**Comment by ryanmoran** [comment]
Resolved by https://github.com/paketo-buildpacks/ruby/pull/703
